services:
  - docker

cache: docker

branches:
  only:
    - master
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

matrix:
  include:
    - env: ARCH=x86_64

install:
  - docker build -t ${DOCKER_USERNAME}/linuxdeploy-plugin-python:${ARCH} --build-arg Arch=${ARCH} .travis

script:
  - docker run --cap-add SYS_ADMIN --device /dev/fuse --mount src=$PWD,dst=/work,type=bind ${DOCKER_USERNAME}/linuxdeploy-plugin-python:${ARCH}
  - python3 -m tests

after_success:
  - ./.travis/after-success.sh
